---
configure_dotfiles: true
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: ~/Development/dotfiles.macos/.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: ~/.config/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

############
# HOMEBREW #
############

# Whether to upgrade homebrew and all packages installed by homebrew.
# If you prefer to manually update packages via brew commands, leave this set to false.
homebrew_upgrade_all_packages: true

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - gh
  - git
  - go
  - gpg
  - htop
  - iperf
  - libevent
  - nmap
  - node
  - nvm
  - openssl
  - php
  - readline
  - ripgrep
  - rustup
  - sqlite
  - ssh-copy-id
  - uv
  - wget
  - zsh-history-substring-search
homebrew_uninstalled_packages:
  - pv

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - bitwarden
  - firefox
  - font-jetbrains-mono-nerd-font
  - handbrake
  - pearcleaner
  - mullvadvpn
  - obs
  - visual-studio-code
  - wezterm
  - zed@preview
homebrew_cask_uninstalled_apps:
  - docker
  - google-chrome
  - dropbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
#composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
#gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
