---
configure_dotfiles: true
configure_sudoers: false
configure_terminal: false
configure_osx: false
configure_dock: false # true to configure the Dock via dockutil.

dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

### Sudoers ###
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

### Dotfiles ###
dotfiles_repo: ~/Development/dotfiles.macos/.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: ~/.config/dotfiles
dotfiles_files:
  - .aliases
  - .environment
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

############
# HOMEBREW #
############

# Whether to upgrade homebrew and all packages installed by homebrew.
# If you prefer to manually update packages via brew commands, leave this set to false.
homebrew_upgrade_all_packages: false

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - awscli
  - bison
  - bun
  - codex
  - gemini-cli
  - gh
  - git
  - go
  - gpg
  - htop
  - ipcalc
  - iperf
  - libevent
  - mas
  - meson
  - ninja
  - nmap
  - node
  - nvm
  - openssl
  - orbstack
  - pnpm
  - php
  - readline
  - repomix
  - ripgrep
  - rustup
  - sgpt
  - sqlite
  - ssh-copy-id
  - telnet
  - uv
  - wget
  - zinit
  - zsh-history-substring-search
homebrew_uninstalled_packages:
  - pv
  - bash-completion

homebrew_taps: 
  - tbckr/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - anydesk
  - blackhole-16ch
  - chromium
  - claude-code
  - companion-satellite
  - firefox
  - font-jetbrains-mono-nerd-font
  - github
  - handbrake
  - IINA
  - mpv
  - mullvadvpn
  - obs
  - obsidian
  - parsec
  - pearcleaner
  - qlmarkdown
  - quicklook-json
  - visual-studio-code
  - vlc
  - wezterm@nightly
  - zed@preview
homebrew_cask_uninstalled_apps:
  - docker
  - dropbox
  - google-chrome
  - wifiman

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 1352778147, name: "Bitwarden" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
#composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
#gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
  - name: claude
    state: latest
    # version: "^1.0.0"
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
